# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: 'npm'
    directory: './packages/base'
    schedule:
      interval: 'weekly'
    target-branch: 'main'
    labels:
      - 'npm dependencies'
      - 'base'

  - package-ecosystem: 'npm'
    directory: './packages/mui'
    schedule:
      interval: 'weekly'
    target-branch: 'main'
    labels:
      - 'npm dependencies'
      - 'mui'

  - package-ecosystem: 'npm'
    directory: './packages/styled-components'
    schedule:
      interval: 'weekly'
    target-branch: 'main'
    labels:
      - 'npm dependencies'
      - 'styled-components'

  - package-ecosystem: 'npm'
    directory: './packages/tailwind'
    schedule:
      interval: 'weekly'
    target-branch: 'main'
    labels:
      - 'npm dependencies'
      - 'tailwind'
