version: 2
updates:
  - package-ecosystem: 'npm'
    directory: './packages/base'
    schedule:
      interval: 'weekly'
    target-branch: 'main'
    labels:
      - 'npm dependencies'
      - 'base'
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-patch']

  - package-ecosystem: 'npm'
    directory: './packages/mui'
    schedule:
      interval: 'weekly'
    target-branch: 'main'
    labels:
      - 'npm dependencies'
      - 'mui'
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-patch']

  - package-ecosystem: 'npm'
    directory: './packages/styled-components'
    schedule:
      interval: 'weekly'
    target-branch: 'main'
    labels:
      - 'npm dependencies'
      - 'styled-components'
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-patch']

  - package-ecosystem: 'npm'
    directory: './packages/tailwind'
    schedule:
      interval: 'weekly'
    target-branch: 'main'
    labels:
      - 'npm dependencies'
      - 'tailwind'
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-patch']
